// Portfolio copy, verbatim. A string is a paragraph; { link: "..." } is a paragraph
// that renders with hyperlink styling but is deliberately not clickable.

export const emails = [
  {
    id: "blanked",
    tag: "Cognitive supplement",
    format: "Story email",
    niche: true,
    subject: "I blanked in front of my biggest client",
    teaser:
      "A 15-second freeze on a call with the biggest client on the books, and what changed the following week.",
    body: [
      "I nearly ruined my whole life. Let me explain.",
      "It was 9am sharp. I had my biggest real estate client's face on my laptop staring at me.",
      "Nothing out of the ordinary, but today something was different.",
      "I felt like there was this little tornado or storm in my head, making incredible amounts of noise.",
      "I couldn't think straight. My words felt like they were coming out of my mouth at 0.5x speed.",
      "I had no idea what was going on. I couldn't even hear what my client was saying.",
      "'CONNLA!!!, what has changed from last month's budget?'",
      "I froze. I was genuinely staring at his face for nearly 15 seconds.",
      "Do you know how long that feels in that scenario?",
      "I blanked. I told him I was sorry and that I was feeling under the weather.",
      "Fast forward to next week. Same time, same call.",
      "However, I just had one of \"nootropics'' new all in one brain blast tablets.",
      "Packed with magnesium, sodium, potassium and 16 other vitamins and minerals that are directly linked to increased cognitive function.",
      "My answers were on point, I was firing them away like it was nothing, and thankfully I didn't lose my client.",
      "I had to learn this the hard way.",
      "But, thanks to me, I can save you from all these horrible scenarios.",
      "Now I know I am selling this to you, but it is for a very good reason.",
      "This will literally save you in important meetings or calls, like it saved me tens of thousands of dollars.",
      "Also, over a month of using these weekly, your brain health will be healthier than ever.",
      "Repeated use is the key.",
      {
        link: "If you want your brain to feel clear as day on your next meeting or presentation at work, this is for you.",
      },
      "Now I am away to drink coffee with my beautiful wife.",
      "See you soon",
      "P.S. Did you know that upon awakening your brain is operating at 40% of its actual speed. With our new brain blast tablets, your brain will feel like it is at 100%",
      { link: "Shop now!" },
      "Connla",
    ],
  },
  {
    id: "crash",
    tag: "Cognitive supplement",
    format: "Get the click",
    niche: true,
    subject: "Your 3pm crash isn't caffeine's fault",
    teaser:
      "Reframes the afternoon crash, then sells the fix without asking anyone to give up their coffee.",
    body: [
      "Let me guess, you're drinking coffee or something else early in the morning.",
      "3pm rolls around and BOOM, you feel like you are ready for bed.",
      "I know that feeling.",
      "The afternoon crash actually is not caused by caffeine though…",
      "Your brain just isn't getting enough fuel in general, so by 3pm you are shattered.",
      "This has you sitting at your laptop with no motivation or discipline for the rest of the working day.",
      "Your focus is completely out the window.",
      "This is horrible for you and will result in poorer and poorer results in your work as this continues.",
      "Your boss is probably noticing this dip in productivity.",
      "However, what if I told you that you could still drink your caffeine as normal, get that boost in the early part of the day, but also have the energy and cognitive focus for hours after?",
      "Seems too good to be true but, I have the answer right here for you.",
      "Introducing Qualia Mind's new brain blast tablets.",
      "This gives you energy that doesn't spike and crash like caffeine does, giving you laser focus all day.",
      {
        link: "So you can finish every email by 4pm, rather than staring at your laptop screen in agony.",
      },
      "Bye",
      "Connla",
    ],
  },
  {
    id: "underdosed",
    tag: "Pre-workout",
    format: "Get the click",
    niche: false,
    subject: "Your pre-workout is probably underdosed (here's how to check)",
    teaser:
      "Sends the reader to go read their own label, then meets them there with the dose that beats it.",
    body: [
      "I know right now you are probably taking some sort of pre-workout…",
      "But how come you still are getting gassed by set 3 in the gym?",
      "Your current off brand stuff will not cut it,",
      "Just look at the back of the tub right now.",
      "What does the label say?",
      "I guarantee it is below the standard 200mg of caffeine that is supposed to get you fired up for your gym session.",
      "You may as well not be taking it all.",
      "This is secretly slowing down all your muscle growth.",
      "Leading to less confidence in your body…",
      "And nearly guaranteeing you won't be as big as the guys you see over by the bench press every day, benching 100kg, 120kg or 140kg.",
      "If you are okay with the above then just click off right now.",
      "However if you are still reading check this out.",
      "We have just launched our new Legion Pulse pre-workout!",
      "Packed with 250mg of caffeine, exceeding all the other brands you have tried previously.",
      "This is designed to keep you running and on high alert throughout your gym session no matter if it's 30 minutes or 3+ hours.",
      "So how about you try it today and come and try all the flavours to ensure you hit those PRs in the future!",
      "Bye for now",
      "Connla",
    ],
  },
  {
    id: "launch",
    tag: "Pre-workout",
    format: "Launch",
    niche: false,
    subject: "We just launched the pre-workout other brands don't want you to see",
    teaser:
      "A launch email that builds the 6pm drop into a reason to open now, with a first-500 bonus.",
    body: [
      "Oh boy am I excited to show you this!",
      "This new product is so good, a brand reached out and told us to delay this announcement.",
      "No can do…",
      "I just know you are going to love it.",
      "One of our legion athletes Ciara certainly did.",
      "She said this was a game changer for her, and now…",
      "She is pushing more reps every single session, especially on them killer leg days.",
      "Would you like to achieve this too?",
      "Well I may just have the answer right here because today at 6pm I am proud to say that here at Legion Athletics we are launching…",
      "Pulse Pre-workout!!",
      "The new science backed pre workout on the market designed to keep you absolutely laser focused in the gym…",
      "Or how does progressing in all your lifts in every single session sound?",
      "You can get this today at 6pm!",
      "However this is a special launch for people who are receiving this email…",
      "The first 500 people to order through the link below in this email get an extra tub completely free!",
      "So you can pack on some lean muscle for twice as long as all the slow buyers who aren't signed up to our special email list.",
      "Now the people in the lab are still finalising some more flavours including wild berry, exotic mango and zesty lime, but they will be out and available to purchase before you know it.",
      "Check out the ones we have available and let us know what they are like.",
      "I can't wait to hear from you!",
      "See you later",
      "Connla",
    ],
  },
  {
    id: "plateau",
    tag: "Pre-workout",
    format: "Success story",
    niche: false,
    subject: "How Brad finally broke his 3-month plateau (one scoop did it)",
    teaser:
      "Hands the whole middle of the email to the customer's own words, then points them at the store.",
    body: [
      "Sometimes the gym can be super annoying.",
      "You're hitting your 150 grams of protein, you're pushing to maximum failure on every exercise…",
      "But some sessions you're just stuck on the same weight as the last time…",
      "Which has your mood right down in the dumps…",
      "All that consistency and hard work outside of the gym, just to still be stuck on these dreaded plateaus.",
      "What would your reaction be if I told you here at the Legion Athletics Family we have created a solution to this!",
      "I am proud to announce that our new Pulse pre workout is now on sale.",
      "Here, just listen to what Brad had to say about it.",
      "'Finally I feel alive!!!'",
      "I tried Pulse for the first time last week before the gym.",
      "Now usually, towards the end of my sessions I am feeling super groggy,",
      "Yawning constantly, head is in my hands…",
      "I can just never seem to find any focus after pushing myself so hard.",
      "This was always resulting in me never progressing in my sets from the last session.",
      "However,",
      "I took 1 scoop of the new Pulse pre workout and I was blown away,",
      "The laser focus I had from the start was insane!",
      "It felt like I was blasting the bench bar straight into the air, it felt like I could literally throw it through the roof.",
      "Even towards the end, the focus and energy was still there.",
      "It was one of my best gym sessions to date.",
      "I progressed on every single exercise, whether it was more sets or even added more weight on.",
      "This is what the gym is all about!",
      "Thank you so much Legion for this. I cannot wait for my next session now!'",
      "WOW Brad I am so pleased to hear that!",
      "This genuinely makes me super happy seeing that here at Legion we are providing everyone with the best supplements to transform their gym performance.",
      "I know you are in the boat of feeling tired and groggy in your sessions, just like Brad.",
      "Brad was stuck on the same reps because of this, but 1 scoop has really changed the game for him.",
      "I want this for you too!",
      "If you are tired of sitting at the weights on all your exercises and want to feel like you are going to throw the bench bar through the roof just like Brad you can buy Pulse pre workout today in our online store.",
      "This is the new wave.",
      "See you soon.",
      "Connla",
    ],
  },
];

export const EMAIL_ADDRESS = "connlagaffney7@gmail.com";
